name: validate-gentx
on:
  pull_request:
    # branches: [dev]
jobs:
  build:
    name: GenTx
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
      - name: pwd
        run: pwd
      - name: Validating...
        run: ./scripts/validate-gentx.sh
